apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mtc-operator.openshift-migration: ""
  name: mtc-operator
  namespace: openshift-migration
  annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-5"
spec:
  channel: release-v1.8
  installPlanApproval: Automatic
  name: mtc-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mtc-operator.v1.8.2